### ISSUE TITLE
Errors in txt sharing context

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1587]
- [x] Introduce blank lines to separate blocks
- [x] Scheduled date is showing Completion date

**Comment by manuelplazaspalacio** [comment]
Trying to share, " ZW HNQIS VMMC"  with 47% points, "ZW HNQIS Family Planing" with 0% points or "ZW HNQIS" with 62% points; with the user ifoche_test2 the app crash
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
                                                                                           at org.eyeseetea.malariacare.layout.score.ScoreRegister.getRecursiveScore(ScoreRegister.java:90)
                                                                                           at org.eyeseetea.malariacare.layout.score.ScoreRegister.getCompositeScore(ScoreRegister.java:116)
                                                                                           at org.eyeseetea.malariacare.data.database.utils.feedback.FeedbackBuilder.build(FeedbackBuilder.java:77)
                                                                                           at org.eyeseetea.malariacare.data.database.utils.feedback.FeedbackBuilder.build(FeedbackBuilder.java:45)
                                                                                           at org.eyeseetea.malariacare.services.SurveyService.getFeedbackItems(SurveyService.java:376)
                                                                                           at org.eyeseetea.malariacare.services.SurveyService.onHandleIntent(SurveyService.java:192)
                                                                                           at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                                           at android.os.HandlerThread.run(HandlerThread.java:65)
