### ISSUE TITLE
Fix demo mode

### ISSUE THREAD

**Issue by ifoche** [ifoche/malariapp#1673]

**Comment by ifoche** [comment]
- [ ] Fragments that are not shown
- [ ] Crashes on never assess

**Comment by idelcano** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.eyeseetea.malariacare.hnqis_ng_bb, PID: 7244
                  java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
                      at org.eyeseetea.malariacare.fragments.PlannedPerOrgUnitFragment$1.run(PlannedPerOrgUnitFragment.java:149)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:5951)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by idelcano** [comment]
11-06 08:19:39.283 org.eyeseetea.malariacare.hnqis_ng_bb E/SQLiteLog: (284) automatic index on OrgUnitProgramRelation(id_org_unit_fk)
11-06 08:19:39.293 org.eyeseetea.malariacare.hnqis_ng_bb I/.Session: putServiceValue(org.eyeseetea.malariacare.services.SurveyService.PLANNED_SURVEYS_ACTION, org.eyeseetea.malariacare.data.database.utils.services.PlannedServiceBundle@203137b7)
11-06 08:19:39.383 org.eyeseetea.malariacare.hnqis_ng_bb E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: org.eyeseetea.malariacare.hnqis_ng_bb, PID: 17498
                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
                                                                               at org.eyeseetea.malariacare.data.database.utils.monitor.MonitorMessagesBuilder.buildJSON(MonitorMessagesBuilder.java:61)
                                                                               at org.eyeseetea.malariacare.data.database.utils.monitor.MonitorMessagesBuilder.addDataInChart(MonitorMessagesBuilder.java:54)
                                                                               at org.eyeseetea.malariacare.fragments.MonitorFragment$2.onPageFinished(MonitorFragment.java:269)
                                                                               at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:199)
                                                                               at org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:72)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:145)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by idelcano** [comment]
Crashes on never assess:

11-06 08:51:22.003 ? E/AndroidRuntime: FATAL EXCEPTION: main
                                       Process: org.eyeseetea.malariacare.hnqis_ng_bb, PID: 30836
                                       java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
                                           at java.util.Calendar.setTime(Calendar.java:1195)
                                           at java.text.SimpleDateFormat.formatImpl(SimpleDateFormat.java:518)
                                           at java.text.SimpleDateFormat.format(SimpleDateFormat.java:820)
                                           at java.text.DateFormat.format(DateFormat.java:307)
                                           at org.eyeseetea.malariacare.utils.AUtils.getEuropeanFormatedDate(AUtils.java:178)
                                           at org.eyeseetea.malariacare.layout.adapters.survey.PlannedAdapter.getViewByPlannedSurvey(PlannedAdapter.java:285)
                                           at org.eyeseetea.malariacare.layout.adapters.survey.PlannedAdapter.getView(PlannedAdapter.java:207)

**Comment by idelcano** [comment]
Android v 5.0.1 (S4)
