### ISSUE TITLE
layout blank

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [ifoche/malariapp#1866]
## User Report
when select action plan in the dialog menu of improve module

## ScreenShot
![file](https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/android_screenshot1096318655.jpg)
## Device Info
```
Time Stamp: 2018-04-09T06:53:30 UTC
App Version: 1.3.1 (42)
Install Source: Unknown
Android Version: 7.0 (24)
Device Manufacturer: XIAOMI
Device Model: REDMI NOTE 4
Display Resolution: 1920x1080
Display Density (Actual): 480dpi
Display Density (Bucket) xxhdpi
---------------------

```

**Comment by idelcano** [comment]
This bug appears after hiden planning tab in settings, and i get this crash: 04-09 08:54:29.875 9945-9945/org.eyeseetea.malariacare.hnqis_ng_dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.eyeseetea.malariacare.hnqis_ng_dev, PID: 9945
    java.lang.IndexOutOfBoundsException: Index: 6, Size: 4
        at java.util.ArrayList.set(ArrayList.java:427)
        at android.app.FragmentManagerImpl.makeInactive(FragmentManager.java:1225)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1129)
        at android.app.FragmentManagerImpl$5.onAnimationEnd(FragmentManager.java:1081)
        at android.animation.AnimatorSet.onChildAnimatorEnded(AnimatorSet.java:829)
        at android.animation.AnimatorSet.-wrap1(AnimatorSet.java)
        at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:784)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1149)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1309)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:685)
        at android.view.Choreographer.doFrame(Choreographer.java:618)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6342)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by ifoche** [comment]
It may be related to #1867, because #1867 happened just after removing the tab hide
