### ISSUE TITLE
Analyze (not solve) pull error with last 2.30 server version

### ISSUE THREAD

**Issue by xurxodev** [ifoche/malariapp#2200]
2018-11-16 11:36:48.115 2966-3070/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: https://latest.psi-mis.org/api/system/info/
2018-11-16 11:36:48.115 2966-3070/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: Body
2018-11-16 11:36:48.391 2966-3070/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: https://latest.psi-mis.org/api/organisationUnitLevels?paging=false&fields=id,displayName,level
2018-11-16 11:36:48.391 2966-3070/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: Body
2018-11-16 11:36:48.714 2966-3072/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: https://latest.psi-mis.org/api/attributes?paging=false&fields=id,name,displayName,created,lastUpdated,code,valueType
2018-11-16 11:36:48.715 2966-3072/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: Body
2018-11-16 11:36:49.040 2966-3074/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: https://latest.psi-mis.org/api/me/?fields=id,created,lastUpdated,name,displayName,firstName,surname,gender,birthday,introduction,education,employer,interests,jobTitle,languages,email,phoneNumber,organisationUnits[id],userCredentials[userRoles[dataSets[id],programs[id,programType]]]
2018-11-16 11:36:49.040 2966-3074/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: Body
2018-11-16 11:36:49.108 2966-3008/org.eyeseetea.malariacare.hnqis_ng_dev D/EGL_emulation: eglMakeCurrent: 0xa9a85ba0: ver 3 0 (tinfo 0xa9a83440)
2018-11-16 11:36:49.134 1635-1656/? I/ActivityManager: Displayed org.eyeseetea.malariacare.hnqis_ng_dev/org.eyeseetea.malariacare.ProgressActivity: +1s282ms
2018-11-16 11:36:49.289 2966-3074/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: https://latest.psi-mis.org/api/organisationUnits?paging=false&fields=id,name,coordinates,displayName,created,lastUpdated,access,path,level,openingDate,programs[id],dataSets[id],attributeValues[*,attribute[name,displayName,created,lastUpdated,access,id,valueType,code]]&filter=id:in:[Cf1y95PndAB,A5HZNrJc2ir,ijCMzF0Ij9E]
2018-11-16 11:36:49.289 2966-3074/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: Body
2018-11-16 11:36:49.696 2966-3074/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: https://latest.psi-mis.org/api/me/?fields=id,created,lastUpdated,name,displayName,firstName,surname,gender,birthday,introduction,education,employer,interests,jobTitle,languages,email,phoneNumber,organisationUnits[id],userCredentials[userRoles[dataSets[id],programs[id,programType]]]
2018-11-16 11:36:49.696 2966-3074/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: Body
2018-11-16 11:36:49.962 2966-3074/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: https://latest.psi-mis.org/api/me/?fields=id,created,lastUpdated,name,displayName,firstName,surname,gender,birthday,introduction,education,employer,interests,jobTitle,languages,email,phoneNumber,organisationUnits[id],userCredentials[userRoles[dataSets[id],programs[id,programType]]]
2018-11-16 11:36:49.962 2966-3074/org.eyeseetea.malariacare.hnqis_ng_dev I/System.out: Body
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err: java.lang.IllegalArgumentException: Specify at least one uid of program to sync
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at org.hisp.dhis.client.sdk.core.program.ProgramControllerImpl.synchronizeProgramsByVersions(ProgramControllerImpl.java:194)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at org.hisp.dhis.client.sdk.core.program.ProgramControllerImpl.pull(ProgramControllerImpl.java:136)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at org.hisp.dhis.client.sdk.core.user.AssignedProgramsControllerImpl.sync(AssignedProgramsControllerImpl.java:96)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at org.hisp.dhis.client.sdk.android.program.UserProgramInteractorImpl$1.call(UserProgramInteractorImpl.java:69)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at org.hisp.dhis.client.sdk.android.program.UserProgramInteractorImpl$1.call(UserProgramInteractorImpl.java:65)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:39)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at org.hisp.dhis.client.sdk.android.api.utils.DefaultOnSubscribe.call(DefaultOnSubscribe.java:34)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.internal.operators.OperatorZip$Zip.start(OperatorZip.java:202)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:143)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:109)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.Subscriber.setProducer(Subscriber.java:209)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:10256)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2018-11-16 11:36:50.188 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev W/System.err:     at java.lang.Thread.run(Thread.java:764)
2018-11-16 11:36:50.189 2966-3073/org.eyeseetea.malariacare.hnqis_ng_dev D/.ProgressActivity: Error while trying to pull metadata from dhis server

**Comment by idelcano** [comment]
@xurxodev  latest is working in  v1.4_hnqis for me.

I see a wrong request in your log:

Your query:
https://latest.psi-mis.org/api/me/?fields=id,created,lastUpdated,name,displayName,firstName,surname,gender,birthday,introduction,education,employer,interests,jobTitle,languages,email,phoneNumber,organisationUnits[id],userCredentials[userRoles[dataSets[id],programs[id,programType]]]

but my query:
https://latest.psi-mis.org/api/30/me?fields=id%2Ccreated%2ClastUpdated%2Cname%2CdisplayName%2CfirstName%2Csurname%2Cgender%2Cbirthday%2Cintroduction%2Ceducation%2Cemployer%2Cinterests%2CjobTitle%2Clanguages%2Cemail%2CphoneNumber%2CorganisationUnits%5Bid%2Cprograms%5Bid%2CprogramType%5D%5D%2CuserCredentials%5BuserRoles%5D%2C%20programs%2C%20dataSets

Is it possible that you were running v1.3, or something similar?

Server info:

User: KEdemo1

Build date: 2018-11-16 02:06

**Comment by xurxodev** [comment]
The buildtime on server has changed and now the pull work, change this issue to invalid
