### ISSUE TITLE
Investigate why permision is not requested sometimes

### ISSUE THREAD

**Issue by xurxodev** [ifoche/malariapp#2209]
Testing on emulator Android api 27:
The permission is not requested and to enter in dashboard after login and pull a crash ocurred:
2018-12-17 07:12:12.906 7921-7921/org.eyeseetea.malariacare.questmark_dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.eyeseetea.malariacare.questmark_dev, PID: 7921
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.eyeseetea.malariacare.questmark_dev/org.eyeseetea.malariacare.DashboardActivity}: java.lang.SecurityException: getDeviceId: Neither user 10106 nor current process has android.permission.READ_PHONE_STATE.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.SecurityException: getDeviceId: Neither user 10106 nor current process has android.permission.READ_PHONE_STATE.
        at android.os.Parcel.readException(Parcel.java:2004)
        at android.os.Parcel.readException(Parcel.java:1950)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:4938)
        at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:1018)
        at org.eyeseetea.malariacare.DashboardActivity.getPhoneMetadata(DashboardActivity.java:131)
        at org.eyeseetea.malariacare.DashboardActivity.loadPhoneMetadata(DashboardActivity.java:143)
        at org.eyeseetea.malariacare.DashboardActivity.onCreate(DashboardActivity.java:98)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by xurxodev** [comment]
@idelcano @ifoche This issue is not finished by manu, we should finish it. I assign it to @idelcano
